# Generated by Django 4.1.7 on 2023-05-30 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Reservas.estadohabitacion'),
        ),
    ]
